export const orugaConfig = {
  iconPack: "",
  iconComponent: "material-icon",
  statusIcon: true,
  button: {
    rootClass: "btn",
    variantClass: "btn-",
    roundedClass: "btn-rounded",
    outlinedClass: "btn-outlined-",
    disabledClass: "btn-disabled",
    sizeClass: "btn-size-",
  },
  field: {
    rootClass: "field",
    labelClass: "field-label",
    messageClass: "text-sm italic",
    variantClass: "field-",
    variantMessageClass: "field-message-",
  },
  input: {
    inputClass: "input",
    roundedClass: "rounded",
    variantClass: "input-",
    iconRightClass: "input-icon-right",
    sizeClass: "input-size-",
  },
  taginput: {
    itemClass: "taginput-item",
    rootClass: "taginput",
    autocompleteClasses: {
      rootClass: "taginput-autocomplete",
      inputClasses: {
        rootClass: "taginput-input-wrapper",
        inputClass: "taginput-input",
      },
    },
  },
  autocomplete: {
    rootClass: "autocomplete",
    itemClass: "autocomplete-item",
    itemGroupTitleClass: "autocomplete-item-group-title",
  },
  icon: {
    variantClass: "icon-",
  },
  checkbox: {
    rootClass: "checkbox",
    inputClass: "checkbox-check",
    inputCheckedClass: "checkbox-checked",
    labelClass: "checkbox-label",
  },
  dropdown: {
    rootClass: "dropdown",
    menuClass: "dropdown-menu",
    itemClass: "dropdown-item",
    itemActiveClass: "dropdown-item-active",
  },
  steps: {
    itemHeaderActiveClass: "steps-nav-item-active",
    itemHeaderPreviousClass: "steps-nav-item-previous",
    stepMarkerClass: "step-marker",
    stepDividerClass: "step-divider",
  },
  datepicker: {
    iconNext: "ChevronRight",
    iconPrev: "ChevronLeft",
    boxClass: "datepicker-box",
  },
  modal: {
    rootClass: "modal",
    contentClass: "modal-content",
  },
  switch: {
    labelClass: "switch-label",
    switchCheckedClass: "switch-check-checked",
  },
  select: {
    selectClass: "select",
  },
  radio: {
    rootClass: "radio",
    inputCheckedClass: "radio-checked",
    inputClass: "form-radio",
    labelClass: "radio-label",
  },
  notification: {
    rootClass: "notification",
    variantClass: "notification-",
  },
  table: {
    tableClass: "table",
    tdClass: "table-td",
    thClass: "table-th",
    rootClass: "table-root",
  },
  pagination: {
    rootClass: "pagination",
    simpleClass: "pagination-simple",
    listClass: "pagination-list",
    infoClass: "pagination-info",
    linkClass: "pagination-link",
    linkCurrentClass: "pagination-link-current",
    linkDisabledClass: "pagination-link-disabled",
    nextButtonClass: "pagination-next",
    prevButtonClass: "pagination-previous",
    ellipsisClass: "pagination-ellipsis",
  },
  tabs: {
    rootClass: "tabs",
    navTabsClass: "tabs-nav",
    navTypeClass: "tabs-nav-",
    navSizeClass: "tabs-nav-",
    itemWrapperClass: "tabs-nav-item-wrapper",
    itemHeaderTypeClass: "tabs-nav-item-",
    itemHeaderActiveClass: "tabs-nav-item-active-",
  },
  tooltip: {
    rootClass: "tooltip",
    contentClass: "tooltip-content",
    arrowClass: "tooltip-arrow",
    variantClass: "tooltip-content-",
  },
};
